apiVersion: v1
kind: Service
metadata:
  labels:
    app: iot-demo
    name: consumer-app
  name: consumer-app
spec:
  ports:
  - name: http
    port: 8081
    protocol: TCP
    targetPort: 8081
  selector:
    name: consumer-app
