---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: iot-demo
    name: consumer-app
  name: consumer-app
spec:
  host: consumer-app.lydemo.com
  port:
    targetPort: 8080
  to:
    kind: Service
    name: consumer-app
    weight: 100
  wildcardPolicy: None
status:
  ingress:
    - conditions:
        - status: 'True'
          type: Admitted
